### ISSUE TITLE
HitBox/HurtBox

### ISSUE THREAD

**Issue by SSebigo** [gdquest-demos/godot-4-3d-third-person-controller#24]
Not really an issue, just a question, why is this project not using hitbox/hurtbox nodes? I understand that maybe because it's a "small" project, so it's not required, but it would've been good to have it just for learning purpose.

**Comment by NathanLovato** [comment]
Just saw this, sorry for the long reply delay.

We never quite skip adding things just because a project is small, but more often because something has no use in the project. I think a fair number of devs add things out of habit, or because they duplicate files from project to project and don't remove the excess.

Here, adding an abstraction for hit and hurt boxes would only add a little complexity without providing benefits. So, I would prefer to show and teach hit and hurt boxes in a different setting, where they make sense. Either in isolation or in a project designed to highlight them.

I'll close because it's more of a discussion/question about the project than an issue, but don't hesitate to add follow up questions.
